⚔️Epic! - PR com as mudanças do Pizza
igorrturano/Epic-Server pull request #213
Opened 2024-10-01 22:02 UTC by filipehb

2024-10-02 02:45 UTC, PizzaUO reviewed
adicionei novas versões para:
lore_items
itemdesc
tooltip
loot- groups
loot-index

estavam todos desatualizados

2024-10-02 03:59 UTC, igorrturano requested changes

2024-10-02 03:59 UTC, igorrturano commented on pkg/items/CUSTOM PIZZA/itens novos/parseCharProfile.src
> +					"hobbit": raca := "Hobbit";
Não existe raça Hobbit

2024-10-02 03:59 UTC, igorrturano commented on pkg/items/CUSTOM PIZZA/itens novos/parseCharProfile.src
> +					"anao":   raca := "Anão";
Pode usar o enum do epicConstants para evitar erros

2024-10-02 03:59 UTC, igorrturano commented on pkg/items/CUSTOM PIZZA/itens novos/parseCharProfile.src
> +// <img src="https://cdn.discordapp.com/attachments/811749265143234617/813042478696366100/2Q.png"  width:200 height:200 align:right> Hannah Black <br><br> Lorem ipsum dolor sit amet. Lorem ipsum dolo
Isso tudo comentado, precisa? Não é melhor deletar, o código já tá grande o suficiente.

2024-10-02 03:59 UTC, igorrturano commented on pkg/items/CUSTOM PIZZA/itens novos/setNPCprofile.src
> +            url := "https://media.discordapp.net/attachments/621351501511524353/1186245051953725450/image.png";
Imagens no discrd somem com o tempo

2024-10-02 03:59 UTC, igorrturano commented on pkg/items/CUSTOM PIZZA/itens novos/setNPCprofile.src
> +            url := "https://media.discordapp.net/attachments/621351501511524353/1186245051953725450/image.png";
essa inclusive já sumiu

2024-10-02 03:59 UTC, igorrturano commented on pkg/items/CUSTOM PIZZA/itens novos/toolTips.src
> +/* $Id: toolTips.src 104 2006-05-25 22:14:15Z montuz $
Parece o nosso toolTip, qual o propósito aqui? Por que não usar o que ja´p temos?

2024-10-02 03:59 UTC, igorrturano commented on pkg/systems/loot/config/loot-index.cfg
> + Random  LoreItems    1   100  // Sempre tenta dropar um item de lore
Atualiza com a develop essa PR, muita coisa desatualizada, vai dar mto conflito

2024-10-02 03:59 UTC, igorrturano commented on pkg/utils/connectors/DiscordWebhook/discord.src
> +  elseif ( tipo == "itemlore" )
Adicionou o webhook, mas ele nao ta sendo chamado

2024-10-02 11:47 UTC, PizzaUO commented on pkg/items/CUSTOM PIZZA/itens novos/parseCharProfile.src
> +					"anao":   raca := "Anão";
ajustado

2024-10-02 11:47 UTC, PizzaUO commented on pkg/items/CUSTOM PIZZA/itens novos/parseCharProfile.src
> +// <img src="https://cdn.discordapp.com/attachments/811749265143234617/813042478696366100/2Q.png"  width:200 height:200 align:right> Hannah Black <br><br> Lorem ipsum dolor sit amet. Lorem ipsum dolo
concordo, o comentado já estava e eu mantive. vou deletar

2024-10-02 11:47 UTC, PizzaUO commented on pkg/items/CUSTOM PIZZA/itens novos/toolTips.src
> +/* $Id: toolTips.src 104 2006-05-25 22:14:15Z montuz $
é o mesmo, acho que eu confundi o eld e não coloquei na pasta certa.
você poderia por favor colocar na pasta certa

pkg\packetHooks\megacliloc

2024-10-02 11:47 UTC, PizzaUO commented on pkg/systems/loot/config/loot-index.cfg
feito. atualizado com a develop

2024-10-02 11:47 UTC, PizzaUO commented on pkg/utils/connectors/DiscordWebhook/discord.src
> +  elseif ( tipo == "itemlore" )
preciso descobrir como chamar

2024-10-02 12:31 UTC, igorrturano commented on pkg/items/CUSTOM PIZZA/itens novos/parseCharProfile.src
> +					"anao":   raca := "Anão";
![image](https://github.com/user-attachments/assets/8258d534-7ba3-41e3-af5c-be06eee60610)
Usa esse cara aí, só dar um include no epicConstants
em vez de escrever POlski, só esrever POLSKI.
Usar o enum, teria eevitado o erro de raça

2024-10-02 13:22 UTC, PizzaUO commented on pkg/items/CUSTOM PIZZA/itens novos/parseCharProfile.src
> +					"anao":   raca := "Anão";
fiquei na duvida se vou simples como nessa função

function GetRace(who)
	var raca := GetObjProperty(who, "raca");
	if (!raca)
		return 0;
	else
		return raca;
	endif
endfunction

ou mais rebuscado

    var raca := GetObjProperty(who, "raca");
    if (raca == error)
        raca := "Desconhecida";
    else
        case (raca)
            RACA.ANAO:    raca := RACA.ANAO;
            RACA.DROW:    raca := RACA.DROW;
            RACA.ELFO:    raca := RACA.ELFO;
            RACA.ORC:     raca := RACA.ORC;
            RACA.HUMANO:  raca := RACA.HUMANO;
            RACA.POLSKI:  raca := RACA.POLSKI;
            default:      raca := "Desconhecida";
        endcase
    endif

2024-10-02 13:24 UTC, PizzaUO commented on pkg/items/CUSTOM PIZZA/itens novos/setNPCprofile.src
> +            url := "https://media.discordapp.net/attachments/621351501511524353/1186245051953725450/image.png";
tirei o link

2024-10-02 13:27 UTC, igorrturano commented on pkg/items/CUSTOM PIZZA/itens novos/parseCharProfile.src
> +					"anao":   raca := "Anão";
O function GetRace ta perfeito.
Esse debaixo ta redundante

2024-10-02 13:53 UTC, PizzaUO commented on pkg/items/CUSTOM PIZZA/itens novos/parseCharProfile.src
> +					"anao":   raca := "Anão";
espero que tenha adicionado certo... fiquei inseguro kk

2024-10-02 13:56 UTC, filipehb commented on pkg/items/CUSTOM PIZZA/itens novos/toolTips.src
> +/* $Id: toolTips.src 104 2006-05-25 22:14:15Z montuz $
posso s

2024-10-02 13:57 UTC, filipehb commented on pkg/items/CUSTOM PIZZA/itens novos/toolTips.src
> +/* $Id: toolTips.src 104 2006-05-25 22:14:15Z montuz $
feito, vou subir logo mais o commit

2024-10-02 14:03 UTC, filipehb commented on pkg/items/CUSTOM PIZZA/itens novos/parseCharProfile.src
> +					"anao":   raca := "Anão";
feito

2024-10-02 14:03 UTC, filipehb commented on pkg/items/CUSTOM PIZZA/itens novos/parseCharProfile.src
> +					"anao":   raca := "Anão";
logo mais subo o commit

2024-10-03 15:27 UTC, filipehb commented on pkg/utils/connectors/DiscordWebhook/discord.src
> +  elseif ( tipo == "itemlore" )
@PizzaUO  deu bom esse?

2024-10-04 10:31 UTC, PizzaUO commented on pkg/utils/connectors/DiscordWebhook/discord.src
> +  elseif ( tipo == "itemlore" )
fala mano, não testei ainda no local. vou testar

2024-10-04 13:53 UTC, filipehb commented on pkg/utils/connectors/DiscordWebhook/discord.src
> +  elseif ( tipo == "itemlore" )
Bora para subir para develop e já testa já no shard de develop

2024-10-04 14:00 UTC, merged