Feat_fix_aiera_combat_and_merchant
igorrturano/Epic-Server pull request #241
Opened 2024-10-03 19:41 UTC by fredcaixeta

Mercador sabe reconhecer um Bjorsk
Fix combate Kobolds
Ajuste de temperatura para maior variacao de falas

2024-10-03 20:56 UTC, igorrturano requested changes

2024-10-03 20:56 UTC, igorrturano commented on pkg/mobiles/merchants/pcmerchant/dblclick.src
> +					var PlayerPovo := GetObjProperty(player, "chardata").povo;
Não existe isso.
Ou é culture ou é raça

2024-10-03 20:56 UTC, igorrturano commented on pkg/mobiles/merchants/pcmerchant/dblclick.src
> +						if (PlayerPovo == "Thuriao")
Não tem povo thuriao

2024-10-03 20:56 UTC, igorrturano commented on pkg/mobiles/merchants/pcmerchant/dblclick.src
> +						if (PlayerPovo == "Thuriao")
LÊ a parte de epicgumpcriacao, vê onde seta cultura e raça, pra você entender melhor isso

2024-10-03 20:56 UTC, igorrturano commented on pkg/mobiles/npcs/thor/handling/thorai.inc
> +               "exemple_response" := "comer carne de drow... sai daqui!!"
Kobolds deveriam temer drows, não?

2024-10-03 22:07 UTC, fredcaixeta commented on pkg/mobiles/npcs/thor/handling/thorai.inc
> +               "exemple_response" := "comer carne de drow... sai daqui!!"
fixed... ainda preciso rever a questão do codigo encontrar o nome dele "Wazouski detesta drow"

2024-10-03 22:40 UTC, fredcaixeta reviewed
updated :)

2024-10-04 01:17 UTC, igorrturano approved these changes

2024-10-04 01:17 UTC, igorrturano commented on pkg/mobiles/merchants/pcmerchant/dblclick.src
> +					if (playerRaca == "humano") // para Povos do Leste, Bjorske e Aiglanos serem diferenciados pelos NPCs
Não é a mesma coisa que só chamar a cultura? Apesar que a IA nao tem o contexto de que Har'oloth são drows né

2024-10-04 11:16 UTC, fredcaixeta commented on pkg/mobiles/merchants/pcmerchant/dblclick.src
> +					if (playerRaca == "humano") // para Povos do Leste, Bjorske e Aiglanos serem diferenciados pelos NPCs
pois é... acho que fazer um NPC chamar drow de Haroloth parece ser meio respeitoso ou muito conhecimento pra um npc vendedor qualquer. Mas voce que manda cara :)

2024-10-04 15:45 UTC, fredcaixeta reviewed
mergear?

2024-10-05 04:49 UTC, igorrturano commented on pkg/mobiles/merchants/pcmerchant/dblclick.src
> +					if (playerRaca == "humano") // para Povos do Leste, Bjorske e Aiglanos serem diferenciados pelos NPCs
![image](https://github.com/user-attachments/assets/4994d4df-38a8-4cf7-9a80-5bfad0661160)
Uma boa prática é usar constants

2024-10-05 04:51 UTC, merged