Feat-npcs-max-iteracao
igorrturano/Epic-Server pull request #277
Opened 2024-10-08 17:51 UTC by fredcaixeta

Adiciona funcao para retonar a acc do jogador, para tratar:
maximo de iteracao do talker com o mesmo jogador (3 iteracoes)

2024-10-09 03:16 UTC, igorrturano requested changes

2024-10-09 03:16 UTC, igorrturano commented on scripts/include/epicNPCUtils.inc
> +    var nearby := ListMobilesNearLocationEx(me.x, me.y, LIST_IGNORE_Z, 30, LISTEX_FLAG_NORMAL + LISTEX_FLAG_HIDDEN + LISTEX_FLAG_CONCEALED, me.realm);
30 tiles de distância ta mto distante, o jogador nem vai ver isso acontecer, vai?
Apesar que quem dita isso é o ListenRange ne?

2024-10-09 03:16 UTC, igorrturano commented on pkg/mobiles/merchants/pctalker/talkercycle.src
> +			var max_speech_with_same_player := 3; // o máximo de falas (por AI ou normal) é de 3 para o MESMO player
Em nenhum momento ta sendo deletado a iteração com o jogador.
Depois q ele interagir 3x com um NPC, ele nunca mais vai ouvir ninguem. Principalmente porq é uma GlobalProperty

Deverias er uma SetObjProperty diretamente no npc, com um CD de 2h talvez.
Dentro de duas horas, falou 3x com o npc, para por 2 h

2024-10-09 17:42 UTC, fredcaixeta commented on pkg/mobiles/merchants/pctalker/talkercycle.src
> +			var max_speech_with_same_player := 3; // o máximo de falas (por AI ou normal) é de 3 para o MESMO player
Salve! Entao... na linha 54 eu coloquei pra iteração voltar pra 1 caso o player seja outro

2024-10-09 17:44 UTC, fredcaixeta commented on scripts/include/epicNPCUtils.inc
> +    var nearby := ListMobilesNearLocationEx(me.x, me.y, LIST_IGNORE_Z, 30, LISTEX_FLAG_NORMAL + LISTEX_FLAG_HIDDEN + LISTEX_FLAG_CONCEALED, me.realm);
Entao Igor... copiei isso aqui da HasPLayerNearMe hahahaha que basicamente é a logica de falar só se tiver player perto. E vai registrar o player por essa funcao. Entao acho que faz sentido manter o mesmo range. Mas, se for mudar, melhor mudar entao as duas funcoes.

2024-10-10 04:21 UTC, Rafael1Ferreira commented on pkg/mobiles/merchants/pctalker/talkercycle.src
> +			var max_speech_with_same_player := 3; // o máximo de falas (por AI ou normal) é de 3 para o MESMO player
<img width="340" alt="image" src="https://github.com/user-attachments/assets/098b66c3-3475-40ae-9aa7-bc594389bd12">

testei ficando parado do lado do bicho, ele fez a contagem de iteração, ams continuo falando depois.

2024-10-10 12:05 UTC, fredcaixeta commented on pkg/mobiles/merchants/pctalker/talkercycle.src
> +			var max_speech_with_same_player := 3; // o máximo de falas (por AI ou normal) é de 3 para o MESMO player
Entao @Rafael1Ferreira... acho que ta certo, digo 'acho' porque nao sei o que cada teste2, teste1 significa. Mas a lógica é o NPC continuar falando, sim. Mas ele só fala com IA-ChatGPT no max 3 vezes com o mesmo player

2024-10-10 12:05 UTC, fredcaixeta commented on pkg/mobiles/merchants/pctalker/talkercycle.src
> +			var max_speech_with_same_player := 3; // o máximo de falas (por AI ou normal) é de 3 para o MESMO player
Ele continua falando porque a funcao HasPlayerNear está retornando true. Até porque tem player perto, mas não vai falar com IA-CHatGPT mais

2024-10-10 16:32 UTC, Rafael1Ferreira commented on pkg/mobiles/merchants/pctalker/talkercycle.src
> +			var max_speech_with_same_player := 3; // o máximo de falas (por AI ou normal) é de 3 para o MESMO player
ah tá, entendi. tinha um comentário na variavel falando que era pra limitar dele falar com ia OU normal. ai, achei que era um limitador geral. suave.

2024-10-10 17:47 UTC, Rafael1Ferreira approved these changes
testado e aprovado

2024-10-11 01:04 UTC, merged