Feat/newdamagesystem
igorrturano/Epic-Server pull request #305
Opened 2024-10-12 00:12 UTC by EvilLink

2024-10-12 18:30 UTC, Rafael1Ferreira commented
<img width="398" alt="image" src="https://github.com/user-attachments/assets/ee6297dc-b917-43fd-9425-1eadf2b29749">
não exatamente qual  o escopo total da mudança, mas aparentemente arcos e bestas ainda estão com problema na animação. aparece essa mensagem e ele atira sem animação nenhuma. a flecah/bolt só voa dele pro alvo e ainda faz barulho de espadada quando pega hehehe.

2024-10-12 20:29 UTC, igorrturano requested changes

2024-10-12 20:29 UTC, igorrturano commented on pkg/systems/combat/itemdesc.cfg
> +	EpicMainDamage	DAMAGE_NONE BOW_HGH DAMAGE_NONE
tem um typo asqui

2024-10-13 20:18 UTC, igorrturano approved these changes

2024-10-13 20:18 UTC, merged