Sistema de Folhas Soltas de Pergaminhos
igorrturano/Epic-Server pull request #318
Opened 2024-10-14 02:50 UTC by PizzaUO

# Implementação do Sistema de Pedaços de Pergaminhos

## Descrição
Este PR implementa um novo sistema de pedaços de pergaminhos no jogo. Os jogadores agora podem coletar diferentes tipos de pedaços de pergaminhos e combiná-los para criar pergaminhos completos com várias funcionalidades.

## Principais Alterações
- Adicionados quatro tipos de pedaços de pergaminhos: Fabricação, Alquimia, Tinta e Magia.
- Implementada uma interface gráfica (gump) para visualizar e gerenciar os pedaços de pergaminhos coletados.
- Criado um sistema de níveis para os pergaminhos completos, baseado na quantidade de pedaços coletados.
- Adicionada funcionalidade para criar pergaminhos completos a partir dos pedaços coletados.
- Implementada lógica para selecionar aleatoriamente receitas ou feitiços para os pergaminhos criados.

## Novos Arquivos
- `pedacosPergaminhos.src`: Contém a lógica principal do sistema.
- Atualizações em `itemdesc.cfg` para definir os novos itens de pedaços de pergaminhos.
- Atualizações em `loot-groups.cfg` e `loot-index.cfg` para incluir os novos itens como possíveis loots.

## Como Testar
1. Colete pedaços de pergaminhos de monstros derrotados ou baús de tesouro.
2. Use um pedaço de pergaminho para abrir a interface gráfica.
3. Verifique se você pode visualizar corretamente todos os pedaços coletados.
4. Tente criar um pergaminho completo quando tiver pedaços suficientes.
5. Verifique se o pergaminho criado tem as propriedades corretas baseadas no tipo e nível.

## Notas Adicionais
- Este sistema adiciona uma nova camada de progressão e recompensas para os jogadores.
- Futuramente, podemos expandir este sistema com mais tipos de pergaminhos ou funcionalidades adicionais.

2024-10-15 13:36 UTC, filipehb commented
Testando...

2024-10-15 14:27 UTC, filipehb requested changes
Não tá dropando de chest e teve um comportamento estranho para spells. Ele botou dois ids diferentes e o id do spell n bate com a school
![image](https://github.com/user-attachments/assets/544b829a-2d84-48ff-8213-65fcf71d2909)

2024-10-16 20:18 UTC, PizzaUO commented
arrumei os baús e o igor explicou que já foi corrigido o problema do mago.

2024-10-16 21:14 UTC, filipehb commented
> arrumei os baús e o igor explicou que já foi corrigido o problema do mago.

blz, amanhã eu testo, pizza :*

2024-10-17 18:05 UTC, filipehb approved these changes
Testado e aprovado

2024-10-17 18:05 UTC, merged