Feat/ajustando logica novo gump spawn
igorrturano/Epic-Server pull request #436
Opened 2024-12-07 20:03 UTC by filipehb

2024-12-07 22:15 UTC, igorrturano requested changes

2024-12-07 22:15 UTC, igorrturano commented on pkg/systems/spawnpoint/spawnPointControl.src
> +  var tier := GetObjProperty(spawnpoint, "Tier") ? GetObjProperty(spawnpoint, "Tier") : "0";
Aqui ta errado. Se não tiver no spawnPoint, ele tem que procurar o padrão do npcdesc.cfg

2024-12-07 22:16 UTC, igorrturano requested changes
Outra coias que seria legal é essa lógica aqui, pro GM não precisar ficar escrevendo :~brainai": ...

	var result := CreateNpcFromTemplate(":epicAI:"+template, loc.x, loc.y, loc.z, props, loc.realm );
	if (!result)
		result := CreateNpcFromTemplate(":brainAI:"+template, loc.x, loc.y, loc.z, props, loc.realm );
		if(!result)
			result := CreateNpcFromTemplate(":merchants:"+template, loc.x, loc.y, loc.z, props, loc.realm );
			if(!result)
				SendSysMessage( who, "NPC Creation Failed: " + result.errortext );
			endif
		endif
	endif

	customizeNpc(result, tier);
	
	
	Esse customizeNpc é importante pra fazer o Tier funcionar

2024-12-10 14:10 UTC, filipehb commented
> Outra coias que seria legal é essa lógica aqui, pro GM não precisar ficar escrevendo :~brainai": ...
> 
> ```
> var result := CreateNpcFromTemplate(":epicAI:"+template, loc.x, loc.y, loc.z, props, loc.realm );
> if (!result)
> 	result := CreateNpcFromTemplate(":brainAI:"+template, loc.x, loc.y, loc.z, props, loc.realm );
> 	if(!result)
> 		result := CreateNpcFromTemplate(":merchants:"+template, loc.x, loc.y, loc.z, props, loc.realm );
> 		if(!result)
> 			SendSysMessage( who, "NPC Creation Failed: " + result.errortext );
> 		endif
> 	endif
> endif
> 
> customizeNpc(result, tier);
> 
> 
> Esse customizeNpc é importante pra fazer o Tier funcionar
> ```

O customize já tinha, vou adicionar esse ifzão

2024-12-10 14:32 UTC, filipehb commented on pkg/systems/spawnpoint/spawnPointControl.src
> +  var tier := GetObjProperty(spawnpoint, "Tier") ? GetObjProperty(spawnpoint, "Tier") : "0";
mas e se n tiver? eu fiz de acordo com esse trecho do arquivo createnpc.src:

`
var tier := text[2] ? text[2] : "0";
`

2024-12-14 15:28 UTC, igorrturano approved these changes

2024-12-14 15:29 UTC, merged